### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by trevorkirpaul** [trevorkirpaul/devHangoutCodingChallenge#1]
Here is a list of what needs to be added to the May Challenge

- [ ]  list of required colors
- [ ]  product details (what is the company selling, VPS tiers)
- [ ] company logo
- [ ] create a 'Grading Scale' that will be used to grade all challenges ^1

-----
1: We can also share the Grading Scale so users can see how they'll be scored
